### ISSUE TITLE
debug in vs code doesn't work out of the box

### ISSUE THREAD

**Issue by jektvik** [xddq/nodejs-typescript-modern-starter#112]
It's kind of what I came here for just to see the same pain I've been experiencing for the last couple of hours unfortunately. 

But fortunately it's not far from operational:

Currently the readme says

> Open code, set a breakpoint in src/index.ts and just start debugging with F5.

That won't do. First you need to build with yarn bundle. Then you can run the debug and hit breakpoints. But if you make changes it will not have them. So then you need wire up the debug script to do build/bundle before debugging but that's what I've been battling with for a few hours now so don't have a solution for you.

**Comment by xddq** [comment]
hey @jektvik,

thanks for letting me know! Having trouble for hours is exactly the feeling I want to avoid with this repo 🙈

I did update the testing part just yesterda, perhaps I missed something. Anyway, I will take a look, fix it and update/enhance the documentation to avoid this for others in the future. Will take a closer look at it probably within the next 2 weeks.

Anyway, glad you at least figured out a way in the end! : )

**Comment by jektvik** [comment]
Thanks and good luck. I think you may benefit from ts-node to execute the code for debugging, thats an additional dependency but only dev.

Then I would also suggest adding some module imports to demo the syntax, because it's generally the biggest painpoint in this ecosystem and where either the debugger or tsx kept complaining depending which you fix (it seemed impossible to satisfy both lol - but if you avoid top level await statements as well then it seems to work at least for me now).

**Comment by xddq** [comment]
should be fixed with changes in https://github.com/xddq/nodejs-typescript-modern-starter/pull/113

reopen if you still have any issues
